import { json } from '@sveltejs/kit';
import { query, queryOne, insert, transaction } from '$lib/server/db.js';
import { requireRole } from '$lib/server/auth.js';
import { recalcProjectProgress, logActivity } from '$lib/server/progress.js';

/** GET /api/projects - List projects */
export async function GET({ locals, url }) {
    const user = locals.user;
    let sql, params;

    if (user.role === 'staff') {
        // Staff only see projects they're assigned to
        sql = `SELECT DISTINCT p.*, u.full_name as manager_name
               FROM projects p
               JOIN users u ON p.manager_id = u.id
               LEFT JOIN tasks t ON t.project_id = p.id AND t.assigned_to = ?
               LEFT JOIN sub_tasks st ON st.project_id = p.id AND st.assigned_to = ?
               LEFT JOIN sub_sub_tasks sst ON sst.project_id = p.id AND sst.assigned_to = ?
               WHERE t.id IS NOT NULL OR st.id IS NOT NULL OR sst.id IS NOT NULL
               ORDER BY p.updated_at DESC`;
        params = [user.id, user.id, user.id];
    } else {
        // Admin and PM see all projects
        sql = `SELECT p.*, u.full_name as manager_name
               FROM projects p
               JOIN users u ON p.manager_id = u.id
               ORDER BY p.updated_at DESC`;
        params = [];
    }

    const projects = await query(sql, params);
    return json(projects);
}

/** POST /api/projects - Create project */
export async function POST({ request, locals }) {
    const user = locals.user;

    if (!requireRole(user, 'admin', 'project_manager')) {
        return json({ error: 'Only admins and project managers can create projects' }, { status: 403 });
    }

    const data = await request.json();
    const { name, description, category, company, department, manager_id, planned_start, planned_end, template_id, notes } = data;

    if (!name?.trim()) {
        return json({ error: 'Project name is required' }, { status: 400 });
    }

    const projectId = await transaction(async (conn) => {
        // Insert project (project_code auto-generated by trigger)
        const [result] = await conn.execute(
            `INSERT INTO projects (name, description, category, company, department, manager_id, planned_start, planned_end, notes, created_by, project_code)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '')`,
            [name, description || null, category || 'Other', company || null, department || null,
             manager_id || user.id, planned_start || null, planned_end || null, notes || null, user.id]
        );
        const projId = result.insertId;

        // Every project gets a Backlog phase (weight 0, doesn't affect progress)
        await conn.execute(
            'INSERT INTO phases (project_id, name, is_backlog, weight, sort_order) VALUES (?, ?, TRUE, 0, -1)',
            [projId, 'Backlog']
        );

        // If template selected, create phases from template
        if (template_id) {
            const [templateItems] = await conn.execute(
                'SELECT name, weight, sort_order FROM phase_template_items WHERE template_id = ? ORDER BY sort_order',
                [template_id]
            );
            for (const item of templateItems) {
                await conn.execute(
                    'INSERT INTO phases (project_id, name, weight, sort_order) VALUES (?, ?, ?, ?)',
                    [projId, item.name, item.weight, item.sort_order]
                );
            }
        }

        // Log activity
        await conn.execute(
            `INSERT INTO activity_log (project_id, user_id, entity_type, entity_id, action, description)
             VALUES (?, ?, 'project', ?, 'created', ?)`,
            [projId, user.id, projId, `Project "${name}" created`]
        );

        return projId;
    });

    const project = await queryOne('SELECT *, (SELECT full_name FROM users WHERE id = manager_id) as manager_name FROM projects WHERE id = ?', [projectId]);
    return json(project, { status: 201 });
}
